# Generated by Django 5.2.3 on 2025-06-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_appointment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ghl_task_id', models.CharField(max_length=100, unique=True)),
                ('contact_id', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('calendar_id', models.CharField(max_length=100)),
                ('location_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GHLUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('calendar_id', models.CharField(blank=True, max_length=50, null=True)),
                ('location_id', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
