# Generated by Django 5.2.3 on 2025-06-26 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ghlappointment_ghluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringAppointmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('total_count', models.PositiveIntegerField()),
                ('original_start_time', models.DateTimeField()),
                ('original_end_time', models.DateTimeField()),
                ('contact_id', models.CharField(max_length=255)),
                ('location_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'recurring_appointment_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='ghlappointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='ghlappointment',
            name='ghl_task_id',
        ),
        migrations.AddField(
            model_name='ghlappointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ghlappointment',
            name='occurrence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghlappointment',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='ghlappointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='ghlappointment',
            table='ghl_appointments',
        ),
        migrations.AddField(
            model_name='ghlappointment',
            name='recurring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.recurringappointmentgroup'),
        ),
        migrations.AddIndex(
            model_name='ghlappointment',
            index=models.Index(fields=['recurring_group', 'occurrence_number'], name='ghl_appoint_recurri_5687f0_idx'),
        ),
        migrations.AddIndex(
            model_name='ghlappointment',
            index=models.Index(fields=['contact_id'], name='ghl_appoint_contact_41dea3_idx'),
        ),
        migrations.AddIndex(
            model_name='ghlappointment',
            index=models.Index(fields=['assigned_to'], name='ghl_appoint_assigne_ce4903_idx'),
        ),
        migrations.AddIndex(
            model_name='ghlappointment',
            index=models.Index(fields=['start_time'], name='ghl_appoint_start_t_485f53_idx'),
        ),
    ]
